/** Apply the SQL under `migrations/` (generated by drizzle-kit, shipped with the package). */
import fs from 'node:fs';
import path from 'node:path';

import { sql } from 'drizzle-orm';
import { migrate } from 'drizzle-orm/postgres-js/migrator';

import { PACKAGE_ROOT } from '../../../core/runtime';
import { readQuery, type Connection, type Db } from './client';

export const MIGRATIONS_DIR = path.join(PACKAGE_ROOT, 'migrations');

// postgres-js answers with an array, pglite with `{ rows }`.
async function query<T>(db: Db, statement: ReturnType<typeof sql>): Promise<T[]> {
  const result = (await readQuery(db, () => db.execute(statement))) as unknown as
    T[] | { rows: T[] };
  return Array.isArray(result) ? result : result.rows;
}

async function applied(db: Db): Promise<number> {
  try {
    const rows = await query<{ n: string }>(
      db,
      sql`select count(*)::text as n from drizzle.__drizzle_migrations`,
    );
    return Number(rows[0]?.n ?? 0);
  } catch {
    return 0;
  }
}

/** Host and database of a connection string, for messages; never the credentials. */
export function describeDatabase(url: string): string {
  try {
    const parsed = new URL(url);
    return `${parsed.hostname}${parsed.pathname}`;
  } catch {
    return 'the database';
  }
}

/** Coder keeps to its own `coder` schema; a `coder` schema it did not create belongs to someone else. */
export async function assertCoderDatabase(db: Db, target: string): Promise<void> {
  if (await applied(db)) return;
  const rows = await query<{ name: string }>(
    db,
    sql`select table_name as name from information_schema.tables where table_schema = 'coder' order by 1`,
  );
  const tables = rows.map(row => row.name);
  if (tables.length)
    throw new Error(
      `${target} already has a "coder" schema with tables (${tables.slice(0, 5).join(', ')}${tables.length > 5 ? ', …' : ''}) that Coder did not create. Point DATABASE_URL elsewhere or drop that schema.`,
    );
}

/** How far the database is from the migrations this package ships. */
export async function migrationStatus(
  db: Db,
): Promise<{ applied: number; pending: number; total: number }> {
  const journal = JSON.parse(
    fs.readFileSync(path.join(MIGRATIONS_DIR, 'meta', '_journal.json'), 'utf8'),
  ) as { entries: Array<{ when: number }> };
  const rows = await query<{ n: string; at: string | null }>(
    db,
    sql`select count(*)::text as n, max(created_at)::text as at from drizzle.__drizzle_migrations`,
  ).catch(() => [] as Array<{ n: string; at: string | null }>);
  const applied = Number(rows[0]?.n ?? 0);
  const latest = Number(rows[0]?.at ?? 0);
  const pending = journal.entries.filter(entry => entry.when > latest).length;
  return { applied, pending, total: journal.entries.length };
}

/** Runs pending migrations; returns how many were applied. */
export async function migrateDb(
  connection: Connection,
  target = 'the database',
): Promise<{ applied: number }> {
  await assertCoderDatabase(connection.db, target);
  const before = await applied(connection.db);
  try {
    await migrate(connection.db, { migrationsFolder: MIGRATIONS_DIR });
  } catch (error) {
    const cause =
      error instanceof Error && 'cause' in error && error.cause instanceof Error
        ? error.cause
        : error;
    throw new Error(
      `Could not migrate ${target}: ${cause instanceof Error ? cause.message : String(cause)}`,
    );
  }
  return { applied: (await applied(connection.db)) - before };
}
